interface utilitySchema {
    landlord:{
        personalDetails:{
            fullname:string,
            email:string,
            phoneNumber:string
        }
        buildings:[
            {
                name:string,
                site:string,
                totalCollections:number,
                netCollections:number,
                totalPaid:number,
                balance:number,
                meters:[
                    {
                        meterNumber:number,
                        utility:string,
                        totalCollections:number,
                        netCollections:number,
                        totalPaid:number,
                        balance:number,
                        paymentsOut:[
                            {
                                date:{
                                    month:string,
                                    year:string 
                                },
                                agentName:string,
                                transactionId:string,
                                amount:number
                            }
                        ],
                        subMeters:[
                            {
                                subMeterNumber:number,
                                utility:string,
                                houseNumber:string,
                                tenantName:string,
                                collections:[
                                    {
                                        date:{
                                            month:string,
                                            year:string 
                                        },
                                        transactionId:string,
                                        amount:number,
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    },

}